apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - namespace.yaml
  - database.yaml
  - valkey-release.yaml
  - secrets.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: paperless-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml