apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actual-budget
resources:
  - namespace.yaml
  - secrets.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: actual-budget-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml